from pathlib import Path
from html import escape

ROOT = Path(__file__).parent
PAGES = ROOT / 'pages'
DOCS = ROOT / 'docs'
HERO = 'assets/img/void-orbit.svg'
ECOSYSTEM = 'assets/img/void-signal.svg'
CASE = 'assets/img/void-fragment.svg'
CULTURE = 'assets/img/void-portrait.webp'
URBAN = 'assets/img/void-urban.webp'

def shell(title, description, body, active=''):
    return f'''<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title} — Black Void</title><meta name="description" content="{description}">
  <link rel="icon" href="assets/img/logo.png">
  <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
  <div id="loader"><img class="ldr-mark" src="assets/img/logo.png" alt=""><div class="ldr-word">BLACK VOID / ARCHIVE</div><div class="ldr-bar"><i></i></div></div>
  <div data-include="../components/menu-superior.html"></div>
  <main>{body}</main>
  <footer><div data-include="../components/menu.html"></div></footer>
  <script src="../components/include.js"></script><script src="assets/js/main.js"></script>
</body></html>'''

def root_shell(title, description, body):
    return f'''<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title} — Black Void</title><meta name="description" content="{description}">
  <link rel="icon" href="pages/assets/img/logo.png">
  <link rel="stylesheet" href="pages/assets/css/style.css">
</head>
<body>
  <div id="loader"><img class="ldr-mark" src="pages/assets/img/logo.png" alt=""><div class="ldr-word">BLACK VOID / ARCHIVE</div><div class="ldr-bar"><i></i></div></div>
  <div data-include="components/menu-superior.html"></div>
  <main>{body}</main>
  <footer><div data-include="components/menu.html"></div></footer>
  <script src="components/include.js"></script><script src="pages/assets/js/main.js"></script><script src="agent/kira.js"></script>
</body></html>'''

def hero(kicker, title, deck, chapter='01'):
    return f'''<section class="page-hero"><div class="wrap"><div class="crumb">BLACK VOID <i>/</i> {chapter}</div><span class="eyebrow reveal">{kicker}</span><h1 class="h-xl reveal" style="margin-top:22px">{title}</h1><p class="lead reveal" style="margin-top:30px">{deck}</p></div></section>'''

def cta(label='Abrir uma conversa'):
    return f'''<section class="cta-block"><div class="wrap"><span class="eyebrow">Próximo capítulo</span><h2 class="reveal" style="margin-top:18px">A complexidade<br>pode <em style="color:var(--void-red);font-style:normal">ceder.</em></h2><a class="btn" href="contato.html">{label} <span aria-hidden="true">↗</span></a></div></section>'''

def chapters(items):
    def tag_markup(values):
        return '<div style="margin-top:20px">' + ''.join(f'<span class="pill">{escape(value)}</span>' for value in values) + '</div>' if values else ''
    return '<div class="chapter-list">' + ''.join(f'''<article class="chapter reveal"><span class="chapter-index">{i:02d} / {label.upper()}</span><div><h3>{title}</h3><p>{desc}</p>{tag_markup(tag_values)}</div></article>''' for i, (label, title, desc, tag_values) in enumerate(items, 1)) + '</div>'

def tags(items):
    return '<div style="margin-top:20px">' + ''.join(f'<span class="pill">{escape(item)}</span>' for item in items) + '</div>'

def scene(config):
    mode = config.get('mode', '')
    if mode == 'ecosystem':
        return '''<section class="scene-section scene-atlas"><div class="wrap"><div class="scene-header"><span class="eyebrow">Mapa de relações</span><span class="meta">BLACK VOID / ATLAS 01</span></div><div class="atlas-stage"><div class="atlas-orbit orbit-one"></div><div class="atlas-orbit orbit-two"></div><div class="atlas-orbit orbit-three"></div><div class="atlas-center"><span class="meta">01</span><strong>UM<br>NÚCLEO</strong><small>e muitas consequências</small></div><div class="atlas-label atlas-north">INTELIGÊNCIA</div><div class="atlas-label atlas-east">PRODUTO</div><div class="atlas-label atlas-south">CONTINUIDADE</div><div class="atlas-label atlas-west">CONFIANÇA</div></div><p class="scene-foot">Uma operação madura não cresce adicionando ferramentas. Cresce aprendendo a fazer com que elas se escutem.</p></div></section>'''
    if mode == 'product':
        return '''<section class="scene-section scene-console"><div class="wrap"><div class="scene-header"><span class="eyebrow">Kira / interface de decisão</span><span class="meta">LIVE CONTEXT / 02</span></div><div class="console-shell"><div class="console-bar"><span class="console-dot"></span><span>KIRA / WORKSPACE</span><span>MEMORY: ACTIVE</span></div><div class="console-body"><aside><span class="meta">AGENTS</span><strong>03</strong><span class="meta">TASKS IN MOTION</span><strong>12</strong><span class="meta">LAST SIGNAL</span><strong>04:28</strong></aside><div class="console-main"><div class="console-question">Como podemos<br><em>destravar</em> este fluxo?</div><div class="console-line"><span>CONTEXT</span><i></i><span>DECISION</span><i></i><span>ACTION</span></div><div class="console-response">Kira encontrou três pontos de fricção, separou o que pode ser automatizado e deixou a decisão final com quem conhece a consequência.</div></div></div></div><p class="scene-foot">A inteligência começa quando o sistema sabe o suficiente para agir — e o bastante para saber quando parar.</p></div></section>'''
    if mode == 'services':
        return '''<section class="scene-section scene-disciplines"><div class="wrap"><div class="scene-header"><span class="eyebrow">O campo de entrega</span><span class="meta">SIX DISCIPLINES / ONE DEPTH</span></div><div class="discipline-wheel"><div class="wheel-core"><span>PROBLEMA</span><strong>→</strong><span>CAPACIDADE</span></div><div class="wheel-label w1">IA</div><div class="wheel-label w2">SOFTWARE</div><div class="wheel-label w3">AUTOMAÇÃO</div><div class="wheel-label w4">INFRA</div><div class="wheel-label w5">SECURITY</div><div class="wheel-label w6">BRANDING</div></div><p class="scene-foot">O valor não está em escolher uma disciplina. Está em entender qual delas precisa abrir a porta.</p></div></section>'''
    if mode == 'flow':
        return '''<section class="scene-section scene-flow"><div class="wrap"><div class="scene-header"><span class="eyebrow">Antes / depois</span><span class="meta">FLOW STUDY / 03</span></div><div class="flow-rail"><div class="flow-point"><span>01</span><strong>Ruído</strong><p>Mensagens, planilhas e decisões que chegam tarde.</p></div><div class="flow-arrow">→</div><div class="flow-point is-active"><span>02</span><strong>Mapa</strong><p>Contexto suficiente para enxergar onde agir.</p></div><div class="flow-arrow">→</div><div class="flow-point"><span>03</span><strong>Ritmo</strong><p>Um sistema que deixa a equipe pensar de novo.</p></div></div></div></section>'''
    if mode == 'proof':
        return '''<section class="scene-section scene-proof"><div class="wrap"><div class="scene-header"><span class="eyebrow">Como uma decisão fica</span><span class="meta">CASE LOG / 04</span></div><div class="proof-grid"><div class="proof-image"><img src="assets/img/void-fragment.svg" alt="Fragmento de construção com diagrama e superfície vermelha" loading="lazy"><span class="meta">OBJECT / AFTER</span></div><div class="proof-notes"><div class="proof-note"><span>01 / TENSÃO</span><strong>Quando a forma antiga já não comporta o próximo movimento.</strong><p>O problema raramente chega com o nome certo. Antes de construir, a gente escuta o que está tentando acontecer.</p></div><div class="proof-note"><span>02 / DECISÃO</span><strong>Escolher uma estrutura que não precise ser defendida todos os dias.</strong><p>Uma boa decisão reduz o número de explicações necessárias para a operação continuar.</p></div><div class="proof-note"><span>03 / PERMANÊNCIA</span><strong>O resultado é a capacidade de seguir sem pedir permissão.</strong><p>É quando a entrega deixa de parecer entrega e começa a funcionar como parte da casa.</p></div></div></div></div></section>'''
    if mode == 'culture':
        return '''<section class="scene-section scene-culture"><div class="wrap"><div class="scene-header"><span class="eyebrow">O que não aparece no organograma</span><span class="meta">CULTURE / 05</span></div><div class="culture-stage"><img src="assets/img/void-creative-work.webp" alt="Mesa de trabalho com materiais e luz baixa" loading="lazy"><div class="culture-stamp"><span>WE BUILD</span><strong>WITH<br>ATTENTION.</strong><span>NOT WITH NOISE.</span></div></div><div class="culture-columns"><p>Somos uma equipe compacta porque proximidade é parte do método. As melhores decisões acontecem quando a pergunta consegue atravessar o espaço entre quem pensa e quem constrói.</p><p>Não trabalhamos para parecer ocupados. Trabalhamos para deixar algo mais claro, mais forte e mais capaz do que estava quando chegamos.</p></div></div></section>'''
    if mode == 'archive':
        return '''<section class="scene-section scene-archive"><div class="wrap"><div class="scene-header"><span class="eyebrow">Arquivo de continuidade</span><span class="meta">FIELD NOTES / 06</span></div><div class="archive-shelves"><div class="archive-shelf"><span>01</span><strong>PERGUNTAS</strong><em>O que precisa ser verdade?</em></div><div class="archive-shelf"><span>02</span><strong>MAPAS</strong><em>Onde a fricção se esconde?</em></div><div class="archive-shelf"><span>03</span><strong>DECISÕES</strong><em>O que merece continuar?</em></div><div class="archive-shelf"><span>04</span><strong>RITUAIS</strong><em>Como o time segue?</em></div></div></div></section>'''
    return ''

def editorial_page(config):
    content = hero(config['kicker'], config['headline'], config['deck'], config.get('chapter', '01'))
    content += scene(config)
    if config.get('image'):
        content += f'''<section><div class="wrap"><div class="split split--wide"><div><span class="eyebrow reveal">Objeto de estudo</span><p class="lead reveal" style="margin-top:24px">{config.get('image_note', 'Uma superfície feita para ser lida de perto: matéria, sinal e decisão na mesma cena.')}</p></div><div class="feature-art reveal"><img src="{config['image']}" alt="{escape(config.get('image_alt', 'Composição editorial Black Void'))}" loading="lazy"><div><span class="tag">FIG. {config.get('chapter', '01')}</span><h3>{config.get('image_title', 'O sistema por trás da superfície.')}</h3></div></div></div></div></section>'''
    if config.get('quote'):
        content += f'''<section><div class="wrap"><div class="quote reveal"><p>{config['quote']}</p><cite>BLACK VOID / NOTA DE ARQUIVO</cite></div></div></section>'''
    if config.get('items'):
        content += f'''<section><div class="wrap"><div class="section-head"><div><span class="eyebrow">{config.get('items_label', 'Estrutura')}</span><h2 class="h-lg" style="margin-top:18px">{config.get('items_title', 'O que muda quando tudo conversa.')}</h2></div><p class="lead">{config.get('items_intro', 'Cada camada tem uma função. Juntas, elas formam uma operação menos fragmentada.')}</p></div>{chapters(config['items'])}</div></section>'''
    if config.get('cards'):
        cards = ''.join(f'<article class="card reveal" style="--i:{i}"><span class="tag">{label}</span><h3>{title}</h3><p>{desc}</p></article>' for i, (label, title, desc) in enumerate(config['cards']))
        content += f'''<section><div class="wrap"><div class="section-head"><div><span class="eyebrow">Seleção</span><h2 class="h-lg" style="margin-top:18px">{config.get('cards_title', 'Uma operação vista por dentro.')}</h2></div></div><div class="grid-3 reveal-stagger">{cards}</div></div></section>'''
    if config.get('table'):
        rows = ''.join(f'<div class="table-row reveal"><span class="num">{i:02d}</span><strong>{name}</strong><p>{desc}</p><span class="tag">{state}</span></div>' for i, (name, desc, state) in enumerate(config['table'], 1))
        content += f'''<section><div class="wrap"><div class="section-head"><div><span class="eyebrow">Mapa operacional</span><h2 class="h-lg" style="margin-top:18px">{config.get('table_title', 'Camadas que sustentam a entrega.')}</h2></div></div><div class="table-list">{rows}</div></div></section>'''
    content += cta(config.get('cta', 'Abrir uma conversa'))
    return shell(config['title'], config.get('description', config['deck']), content)

def home_page():
    body = '''<section class="home-hero"><div class="home-hero-orbit" aria-hidden="true"><span></span><span></span><span></span></div><div class="wrap"><div class="home-index reveal"><span>00 / ABERTURA</span><span>ARQUIVO VIVO / 2026</span></div><div class="home-hero-art reveal"><img src="pages/assets/img/void-orbit.svg" alt="Artefato orbital preto cortado por uma linha de luz vermelha" /><div class="home-art-caption"><span>FIG. 00</span><span>INTELLIGENCE AS MATERIAL</span></div></div><div class="home-copy"><span class="eyebrow reveal">Black Void / casa de construção</span><h1 class="home-title reveal">A complexidade<br>também pode ser<br><em>bonita.</em></h1><p class="home-deck reveal">Nós construímos o que fica entre uma ideia e sua capacidade de continuar existindo: inteligência, produto, software, infraestrutura, segurança e uma linguagem que faz tudo parecer parte do mesmo organismo.</p><div class="actions reveal"><a class="btn" href="pages/contato.html">Entrar no arquivo <span>↗</span></a><a class="btn ghost" href="pages/ecossistema.html">Ver como se conecta</a></div></div><div class="home-scroll"><span class="home-scroll-line"></span><span>DESLIZE PARA LER</span></div></div></section><div class="marquee"><div class="marquee-track"><span><i>—</i>INTELIGÊNCIA</span><span><i>—</i>SOFTWARE</span><span><i>—</i>INFRAESTRUTURA</span><span><i>—</i>DESIGN</span><span><i>—</i>SEGURANÇA</span><span><i>—</i>PERTENCIMENTO</span><span><i>—</i>INTELIGÊNCIA</span><span><i>—</i>SOFTWARE</span><span><i>—</i>INFRAESTRUTURA</span><span><i>—</i>DESIGN</span><span><i>—</i>SEGURANÇA</span><span><i>—</i>PERTENCIMENTO</span></div></div>'''
    body += '''<section class="manifesto-section"><div class="wrap"><div class="manifesto-grid"><div class="manifesto-aside reveal"><span class="eyebrow">Uma nota antes de começar</span><span class="manifesto-number">01</span><span class="meta">O FUTURO NÃO É UM LUGAR.<br>É UMA FORMA DE OPERAR.</span></div><div class="manifesto-copy reveal"><p class="manifesto-lede">Existem empresas que fazem coisas. E existem lugares que tornam outras coisas possíveis.</p><p>Black Void nasceu para a segunda categoria. Trabalhamos no intervalo onde uma intenção ainda não virou produto, onde uma operação ainda não encontrou seu ritmo, onde o time sabe que pode fazer melhor mas não sabe por onde atravessar.</p><p>O nosso trabalho é entrar sem fazer barulho, encontrar a estrutura escondida e construir uma versão dela que o futuro consiga sustentar.</p><a class="text-link" href="pages/sobre.html">Ler a origem da casa <span>↗</span></a></div></div></div></section>'''
    body += f'''<section class="home-ecosystem"><div class="wrap"><div class="section-head"><div><span class="eyebrow">O organismo</span><h2 class="h-lg">Nada existe<br>sozinho.</h2></div><p class="lead">A Black Void é feita de camadas que se escutam. Quando uma muda, todas as outras ganham uma nova responsabilidade.</p></div><div class="ecosystem-scene"><div class="ecosystem-image reveal"><img src="pages/assets/img/void-signal.svg" alt="Mapa visual de sinais conectando contexto, decisão, sistema e continuidade" loading="lazy"><div class="ecosystem-image-label"><span>FIG. 01</span><span>THE LIVING SYSTEM</span></div></div><div class="ecosystem-core reveal"><div class="core-ring ring-a"></div><div class="core-ring ring-b"></div><div class="core-node"><img src="pages/assets/img/logo.png" alt=""><span>BLACK<br>VOID</span></div><span class="node-label node-top">KIRA / INTELLIGENCE</span><span class="node-label node-right">STUDIO / PRODUCT</span><span class="node-label node-bottom">CLOUD / CONTINUITY</span><span class="node-label node-left">SECURITY / TRUST</span></div></div><div class="ecosystem-footer"><span class="meta">09 MÓDULOS / 01 OPERAÇÃO</span><a class="text-link" href="pages/ecossistema.html">Abrir o ecossistema <span>↗</span></a></div></div></section>'''
    body += '''<section class="home-quote-section"><div class="wrap"><div class="quote quote--large reveal"><p>Não queremos ser<br>a sua agência.<br>Queremos ser o lugar<br>onde a próxima coisa<br><em>se torna possível.</em></p><cite>BLACK VOID / MANIFESTO 00</cite></div></div></section>'''
    body += '''<section class="home-services"><div class="wrap"><div class="section-head"><div><span class="eyebrow">O que construímos</span><h2 class="h-lg">A forma muda.<br>A intenção fica.</h2></div><p class="lead">Seis portas de entrada para a mesma pergunta: o que precisa se tornar mais capaz?</p></div><div class="home-service-list"><a class="home-service reveal" href="pages/ia.html"><span>01</span><strong>Inteligência artificial</strong><em>Dar contexto à máquina.</em><span>↗</span></a><a class="home-service reveal" href="pages/desenvolvimento.html"><span>02</span><strong>Desenvolvimento</strong><em>Dar corpo à intenção.</em><span>↗</span></a><a class="home-service reveal" href="pages/automacao.html"><span>03</span><strong>Automação</strong><em>Dar espaço ao humano.</em><span>↗</span></a><a class="home-service reveal" href="pages/infraestrutura.html"><span>04</span><strong>Infraestrutura</strong><em>Dar continuidade ao que importa.</em><span>↗</span></a><a class="home-service reveal" href="pages/cybersecurity.html"><span>05</span><strong>Cybersecurity</strong><em>Dar confiança ao movimento.</em><span>↗</span></a><a class="home-service reveal" href="pages/branding.html"><span>06</span><strong>Branding</strong><em>Dar uma forma que permaneça.</em><span>↗</span></a></div></div></section>'''
    body += '''<section class="home-belonging"><div class="wrap"><div class="belonging-image reveal"><img src="pages/assets/img/void-portrait.webp" alt="Retrato em sombra de uma pessoa que observa uma superfície iluminada" loading="lazy"><div class="belonging-overlay"><span class="eyebrow">Se você chegou até aqui</span><h2>Talvez você<br>também esteja<br>procurando <em>uma casa.</em></h2></div></div><div class="belonging-copy reveal"><p>Para construir algo raro, é preciso estar em um lugar onde perguntas difíceis não sejam tratadas como atraso. Onde o detalhe não seja luxo. Onde a ambição venha acompanhada de responsabilidade.</p><a class="btn" href="pages/team.html">Conhecer quem constrói <span>↗</span></a><a class="text-link" href="pages/carreira.html">Ou descobrir como fazer parte <span>↗</span></a></div></div></section>'''
    body += '''<section class="home-final"><div class="wrap"><span class="eyebrow">Última nota</span><h2 class="home-final-title reveal">O que você<br>quer tornar<br><em>possível?</em></h2><p class="lead reveal">Você não precisa trazer uma resposta pronta. Só precisa trazer a pergunta que não deixa você em paz.</p><a class="btn reveal" href="pages/contato.html">Abrir uma conversa <span>↗</span></a><span class="home-final-mark">BV / 00—∞</span></div></section>'''
    return root_shell('Black Void', 'A Black Void constrói inteligência, produto, software, infraestrutura e sistemas que tornam o futuro operável.', body)

COMMON = {
 'ecossistema': dict(title='Ecossistema', kicker='Arquitetura de operação', chapter='01', headline='Um núcleo para<br>operar sem <em style="color:var(--void-red);font-style:normal">fragmentação.</em>', deck='A Black Void conecta inteligência, produto, automação, infraestrutura e defesa em uma arquitetura que pode crescer sem multiplicar a fricção.', image=ECOSYSTEM, image_alt='Esfera mineral com anéis orbitais em composição editorial', image_title='Uma arquitetura viva.', image_note='Não é uma lista de serviços. É uma relação entre camadas: cada módulo fica mais forte quando sabe onde o outro começa.', quote='O futuro não chega como uma ferramenta. Chega como uma <em>operação inteira.</em>', items_title='Nove módulos. Um movimento.', items=[('Kira AI','A camada que entende.','Agentes e assistentes para transformar intenção em execução.', ['Agentes','Memória','Visão']),('Studio','A camada que materializa.','Produtos digitais, sistemas e experiências que dão forma à estratégia.', ['SaaS','Interfaces','APIs']),('Cloud','A camada que sustenta.','Infraestrutura preparada para crescer, observar e se recuperar.', ['Deploy','Backups','Escala']),('Security','A camada que protege.','Defesa como prática contínua, não como etapa depois do incidente.', ['Pentest','LGPD','Monitoramento'])], cta='Mapear uma operação'),
 'kira': dict(title='Kira AI', kicker='Produto principal', chapter='02', headline='A interface para<br>uma empresa que<br><em style="color:var(--void-red);font-style:normal">pensa em sistemas.</em>', deck='Kira é uma camada de inteligência para organizar contexto, acionar ferramentas e devolver movimento para equipes que não querem escolher entre autonomia e controle.', image=HERO, image_alt='Figura abstrata diante de um núcleo vermelho', image_title='Não é um chat. É uma camada de decisão.', image_note='A interface desaparece quando o sistema começa a fazer sentido. Kira existe para aproximar contexto, ação e revisão.', quote='Memória sem contexto é arquivo. Contexto com ação é <em>infraestrutura.</em>', items_title='O que Kira faz quando a conversa termina.', items=[('01','Memória de trabalho','Contexto preservado entre tarefas, pessoas e decisões.', ['Contexto','Histórico','Permissões']),('02','Agentes','Tarefas decompostas em movimentos observáveis e revisáveis.', ['Orquestração','Aprovação','Logs']),('03','Integrações','Conexões com os sistemas que já sustentam a operação.', ['APIs','CRM','Automação'])], cta='Conhecer a Kira'),
 'servicos': dict(title='Serviços', kicker='Disciplinas de entrega', chapter='03', headline='Seis disciplinas.<br>Uma <em style="color:var(--void-red);font-style:normal">operação.</em>', deck='Do primeiro mapa ao sistema em produção, a Black Void atua nas camadas que transformam um problema difuso em uma capacidade concreta.', items_title='A entrega não termina na tela.', items=[('IA','Agentes que trabalham, não apenas respondem.','RAG, visão computacional, assistentes especializados e modelos aplicados ao contexto real.', ['RAG','Agentes','OCR']),('Software','Intenção que vira ferramenta.','Sites, sistemas, SaaS, APIs e produtos que sobrevivem à primeira versão.', ['SaaS','APIs','Sistemas']),('Automação','Processos que não pedem licença.','Fluxos entre canais, equipes, dados e sistemas com pontos claros de aprovação.', ['WhatsApp','CRM','ERP']),('Infra','A base que fica quando ninguém está olhando.','Deploy, observabilidade, backup, CI/CD, cloud e servidores preparados.', ['Cloud','Docker','CI/CD']),('Security','Defesa antes do alarme.','Pentest, hardening, análise de vulnerabilidade e resposta orientada a risco.', ['Pentest','LGPD','Hardening']),('Branding','Uma marca que continua quando a tela apaga.','Identidade, interface, motion e linguagem visual para produtos com gravidade.', ['UI','UX','Motion'])], cta='Escolher uma disciplina'),
 'portfolio': dict(title='Portfólio', kicker='Trabalho em movimento', chapter='04', headline='O trabalho que<br>fica depois da<br><em style="color:var(--void-red);font-style:normal">apresentação.</em>', deck='Portfólio não é vitrine de efeitos. É o registro de como uma decisão ganhou forma, reduziu ruído e criou uma capacidade que permanece.', image=CASE, image_alt='Artefato arquitetônico com feixe vermelho', image_title='Cases como objetos de estudo.', quote='A melhor interface de um projeto é aquilo que ele torna <em>possível.</em>', cards_title='Seleção de projetos', cards=[('SIGNAL / 2026','Uma camada de decisão para operações complexas.','Sistema editorial e produto interno para organizar sinais, prioridades e ações.'),('ARCO / 2025','Da marca fragmentada ao sistema legível.','Identidade, site e linguagem para uma empresa de infraestrutura que precisava parecer tão sólida quanto operava.'),('NEXO / 2025','Automação sem esconder o humano.','Fluxos integrados com pontos de revisão e métricas que a equipe consegue realmente usar.')], cta='Apresentar um desafio'),
 'casos': dict(title='Cases', kicker='Problema / decisão / sistema', chapter='05', headline='O que muda<br>quando a ideia<br>entra em <em style="color:var(--void-red);font-style:normal">operação.</em>', deck='Cada caso começa com uma tensão concreta. O resultado não é uma peça isolada, mas um sistema que dá ao time mais clareza para seguir.', table_title='Casos em arquivo', table=[('Signal','Camada de decisão para operações críticas.','SISTEMA'),('Arco','Reenquadramento de marca e interface.','IDENTIDADE'),('Nexo','Automação orientada por revisão humana.','FLUXO'),('Noir','Infraestrutura e observabilidade para produto digital.','CLOUD')], quote='Não mostramos apenas o que fizemos. Mostramos a <em>mudança de estado.</em>', cta='Começar um caso'),
 'sobre': dict(title='Sobre', kicker='A casa por trás do sistema', chapter='06', headline='O vazio é espaço<br>para <em style="color:var(--void-red);font-style:normal">construir.</em>', deck='Black Void é um estúdio de inteligência, software e infraestrutura para empresas que preferem operar com profundidade em vez de acumular camadas.', image=CULTURE, image_alt='Colaboradores em silhueta sobre uma mesa iluminada', image_title='Uma equipe pequena para problemas que não são.', image_note='Trabalhamos entre estratégia e execução: lemos o problema, desenhamos a arquitetura e ficamos perto do que acontece depois do lançamento.', quote='A profundidade não é uma estética. É o tempo que uma equipe decide <em>permanecer</em> diante do problema.', items_title='Como pensamos', items=[('01','Começamos pelo sistema.','Antes da tela, entendemos o fluxo, a responsabilidade e o que precisa continuar funcionando.', ['Contexto','Risco','Ritmo']),('02','Projetamos com presença.','A linguagem visual, o produto e a operação precisam dizer a mesma coisa.', ['Marca','Produto','Equipe']),('03','Construímos para o depois.','A primeira entrega abre caminho para a próxima, sem deixar o time dependente da agência.', ['Handover','Documentação','Evolução'])], cta='Conhecer a equipe'),
 'team': dict(title='Team', kicker='Pessoas por trás do arquivo', chapter='07', headline='Pessoas que<br>transformam<br>complexidade em <em style="color:var(--void-red);font-style:normal">movimento.</em>', deck='A Black Void reúne produto, engenharia, IA, design e infraestrutura em uma equipe compacta, curiosa e próxima do problema real.', image=CULTURE, image_alt='Retrato editorial abstrato de uma equipe', image_title='O trabalho também é uma forma de cultura.', cards_title='Papéis que se encontram', cards=[('DIREÇÃO','Estratégia e narrativa','Define o que precisa ser percebido, medido e lembrado.'),('ENGENHARIA','Software e infraestrutura','Transforma arquitetura em sistemas que continuam de pé.'),('INTELIGÊNCIA','IA e automação','Conecta modelos, ferramentas, dados e decisão.'),('DESIGN','Marca e experiência','Dá forma, ritmo e clareza para tudo que chega ao usuário.')], cta='Falar com a equipe'),
 'carreira': dict(title='Carreira', kicker='Trabalho em profundidade', chapter='08', headline='Construa o futuro<br>sem precisar<br><em style="color:var(--void-red);font-style:normal">simplificá-lo.</em>', deck='Estamos interessados em pessoas que gostam de aprender o suficiente para atravessar áreas: entender o problema, testar uma hipótese e deixar o sistema melhor do que encontrou.', quote='Não procuramos peças para preencher uma vaga. Procuramos pessoas que aumentem o campo de <em>possibilidades.</em>', items_title='O que valorizamos', items=[('01','Pensamento sistêmico','Você consegue ver a relação entre uma decisão pequena e o comportamento de uma operação inteira.', ['Curiosidade','Contexto']),('02','Execução cuidadosa','Você prefere uma solução legível e sustentável a uma demonstração rápida que não sobrevive.', ['Rigor','Entrega']),('03','Autoria compartilhada','Você assume responsabilidade sem transformar conhecimento em território.', ['Clareza','Generosidade'])], cards_title='No momento', cards=[('ARQUIVO','Sem vagas abertas','O melhor caminho é enviar um portfólio ou uma nota curta sobre o problema que você gostaria de resolver.'),('SINAL','Banco de talentos','Quando uma frente fizer sentido, voltamos com contexto, não com um formulário genérico.')], cta='Enviar uma apresentação'),
 'blog': dict(title='Blog', kicker='Notas de arquivo', chapter='09', headline='Ideias para<br>quem constrói o<br><em style="color:var(--void-red);font-style:normal">próximo sistema.</em>', deck='Notas curtas sobre IA, produto, infraestrutura, design e as decisões que ninguém vê quando uma operação parece simples.', cards_title='Cadernos recentes', cards=[('01 / IA','A diferença entre modelo e sistema.','Um modelo responde. Um sistema sabe quando perguntar, lembrar, agir e parar.'),('02 / PRODUTO','O que o usuário não deveria precisar entender.','Complexidade bem projetada não desaparece: ela deixa de pedir esforço desnecessário.'),('03 / INFRA','A parte invisível também tem uma linguagem.','Observabilidade, backup e escala são experiência quando o produto depende deles.')], cta='Propor uma pauta'),
 'recursos': dict(title='Recursos', kicker='Materiais de trabalho', chapter='10', headline='Peças para<br>pensar, decidir<br>e <em style="color:var(--void-red);font-style:normal">construir.</em>', deck='Um arquivo em crescimento com checklists, mapas, modelos e perguntas para equipes que querem começar com mais clareza.', cards_title='O que você pode levar', cards=[('MAPA','Briefing de sistema','As perguntas que organizam um problema antes de transformá-lo em escopo.'),('LISTA','Auditoria de presença digital','Um roteiro para encontrar ruído entre marca, interface e operação.'),('GUIA','Primeiro projeto com IA','Como escolher um caso de uso sem transformar a tecnologia em espetáculo.')], cta='Pedir um recurso'),
 'faq': dict(title='FAQ', kicker='Perguntas que abrem o projeto', chapter='11', headline='Dúvidas boas<br>não pedem<br><em style="color:var(--void-red);font-style:normal">atalhos.</em>', deck='Respostas diretas para as perguntas que aparecem antes de uma parceria começar. Se a sua não estiver aqui, podemos começar por ela.', items_title='O que costuma vir antes', items=[('01','A Black Void trabalha com empresas de qualquer tamanho?','Sim, desde que exista um problema com consequência real e abertura para construir uma solução proporcional ao contexto.', []),('02','Vocês entregam apenas design?','Não. Design é uma das camadas. Dependendo do caso, atuamos também em produto, IA, software, automação, infraestrutura e segurança.', []),('03','Como começa um projeto?','Começa com uma conversa curta e um diagnóstico. Depois definimos a hipótese, a primeira entrega e o que precisa ser medido.', []),('04','Vocês trabalham com ferramentas existentes?','Sim. Preferimos integrar o que já funciona antes de reconstruir sem necessidade. A arquitetura precisa servir à operação.', [])], cta='Fazer outra pergunta'),
 'planos': dict(title='Planos', kicker='Formas de começar', chapter='12', headline='Escolha o nível<br>de <em style="color:var(--void-red);font-style:normal">operação.</em>', deck='Não existe uma tabela que substitua contexto. Estes formatos ajudam a nomear o tipo de parceria; o escopo real nasce do diagnóstico.', cards_title='Três pontos de entrada', cards=[('STUDIO','Uma frente, uma entrega','Para marcas e produtos que precisam de uma intervenção concentrada em design, site ou primeira automação.'),('SYSTEM','Um sistema em movimento','Para equipes que precisam conectar produto, IA, software e operação em uma frente contínua.'),('FRONTIER','Uma capacidade nova','Para problemas que exigem pesquisa, protótipo, arquitetura e acompanhamento mais próximo.')], quote='O melhor plano é aquele que deixa a próxima decisão mais <em>clara.</em>', cta='Conversar sobre escopo'),
 'tecnologias': dict(title='Tecnologias', kicker='Base técnica', chapter='13', headline='O que tem<br>por baixo<br><em style="color:var(--void-red);font-style:normal">importa.</em>', deck='Ferramentas são escolhas de contexto. A tecnologia certa é aquela que torna o sistema mais legível, observável e capaz de evoluir.', table_title='Mapa de stack', table=[('Frontend','React, Next, HTML semântico, interfaces responsivas.','INTERFACE'),('Backend','Node, Python, APIs, jobs e serviços modulares.','SERVIÇO'),('IA','Modelos, RAG, embeddings, visão e agentes.','INTELIGÊNCIA'),('Infra','Docker, Linux, cloud, CDN, observabilidade e backup.','OPERAÇÃO'),('Dados','Postgres, filas, eventos, dashboards e auditoria.','CONTEXTO')], cta='Falar sobre arquitetura'),
 'infraestrutura': dict(title='Infraestrutura', kicker='A camada invisível', chapter='14', headline='A base que<br>não pode<br><em style="color:var(--void-red);font-style:normal">cair.</em>', deck='Infraestrutura é o que permite que uma boa ideia continue sendo uma boa experiência quando o tráfego, a equipe e a complexidade aumentam.', image=ECOSYSTEM, image_alt='Esfera mineral em rede orbital', image_title='A confiança mora nos bastidores.', items_title='O que sustentamos', items=[('01','Deploy e escala','Automatizar a passagem entre código, ambiente e produção com clareza.', ['CI/CD','Docker','Cloud']),('02','Observabilidade','Saber o que aconteceu, onde e com qual consequência antes de receber um alerta.', ['Logs','Métricas','Tracing']),('03','Continuidade','Backups, recuperação e redundância tratados como parte do produto.', ['Backup','Recovery','SLA'])], cta='Mapear a infraestrutura'),
 'cybersecurity': dict(title='Cybersecurity', kicker='Defesa contínua', chapter='15', headline='A defesa começa<br>antes do <em style="color:var(--void-red);font-style:normal">alarme.</em>', deck='Segurança não é uma camada que se adiciona no final. É o modo como dados, acessos, infraestrutura e pessoas são desenhados desde o primeiro movimento.', quote='Uma operação segura é aquela que sabe o que protege, por que protege e o que fará quando algo <em>mudar.</em>', items_title='Da superfície ao risco', items=[('01','Visibilidade','Mapear superfícies, acessos, dependências e pontos que normalmente ficam fora da conversa.', ['Asset map','Acesso','Risco']),('02','Resistência','Hardening, políticas, segregação e práticas que reduzem o espaço para um incidente.', ['Hardening','Firewall','LGPD']),('03','Resposta','Preparar investigação, comunicação e recuperação antes de precisar improvisar.', ['SIEM','Playbook','Backup'])], cta='Conversar sobre segurança'),
 'ia': dict(title='Inteligência Artificial', kicker='Sistemas que aprendem', chapter='16', headline='Modelos são<br>matéria-prima.<br>O sistema é o <em style="color:var(--void-red);font-style:normal">produto.</em>', deck='Aplicamos IA onde ela reduz tempo, melhora decisão ou abre uma capacidade que antes não existia — sempre com contexto, limites e revisão.', image=HERO, image_alt='Núcleo vermelho em composição abstrata', image_title='A diferença está na camada de decisão.', items_title='Como a inteligência entra', items=[('01','Entender','RAG, OCR, visão e memória para organizar o contexto certo.', ['RAG','OCR','Visão']),('02','Agir','Agentes e ferramentas para executar tarefas sem transformar autonomia em caixa-preta.', ['Agentes','Tools','Aprovação']),('03','Aprender','Métricas, feedback e observabilidade para que o sistema melhore sem perder rastreabilidade.', ['Evals','Feedback','Logs'])], cta='Encontrar um caso de uso'),
 'automacao': dict(title='Automação', kicker='Fluxos que continuam', chapter='17', headline='Processos que<br>não pedem<br><em style="color:var(--void-red);font-style:normal">licença.</em>', deck='Automação boa não esconde o trabalho. Ela organiza os caminhos repetitivos para que a equipe consiga dedicar energia ao que exige julgamento.', items_title='Onde o fluxo ganha espaço', items=[('01','Conectar','WhatsApp, e-mail, CRM, ERP e planilhas falando com clareza.', ['APIs','Webhooks','CRM']),('02','Decidir','Regras, aprovações e exceções visíveis para o time.', ['Regras','Aprovação','Alertas']),('03','Acompanhar','Logs, responsáveis e métricas para que o automático continue confiável.', ['Logs','KPI','Auditoria'])], cards_title='Padrões que evitamos', cards=[('SEM CAIXA-PRETA','Fluxos observáveis','Toda automação precisa explicar o que fez e por quê.'),('SEM FRAGILIDADE','Fallbacks reais','Quando uma integração falha, a operação precisa saber como seguir.'),('SEM EXCESSO','Automatizar com critério','Nem tudo que é repetitivo precisa virar robô.')], cta='Desenhar um fluxo'),
 'desenvolvimento': dict(title='Desenvolvimento', kicker='Produto em produção', chapter='18', headline='Intenção que<br>vira <em style="color:var(--void-red);font-style:normal">ferramenta.</em>', deck='Construímos produtos digitais que dão forma à estratégia e continuam legíveis quando a primeira versão deixa de ser novidade.', image=CASE, image_alt='Artefato arquitetônico com camada de vidro', image_title='Software como decisão materializada.', items_title='Do mapa ao produto', items=[('01','Descobrir','Entender usuários, contexto, restrições e o que precisa ser verdade.', ['Pesquisa','Mapa','Hipótese']),('02','Construir','Projetar, desenvolver e testar em ciclos que mantêm a direção visível.', ['UI','Código','QA']),('03','Evoluir','Documentar, medir e deixar o time mais capaz do que estava no início.', ['Handover','Métrica','Roadmap'])], cta='Começar um produto'),
 'branding': dict(title='Branding', kicker='Sistema de presença', chapter='19', headline='Uma marca que<br>continua quando<br>a tela <em style="color:var(--void-red);font-style:normal">apaga.</em>', deck='Identidade não é acabamento. É a forma como estratégia, produto, linguagem e comportamento se tornam reconhecíveis em todos os pontos de contato.', image=CULTURE, image_alt='Composição editorial de colaboração', image_title='Presença é coerência em movimento.', items_title='O que fica depois do logo', items=[('01','Posicionamento','Uma frase que organiza escolha, público e diferença sem virar slogan vazio.', ['Essência','Oferta','Público']),('02','Linguagem','Tipografia, cor, imagem, voz e ritmo que tornam a marca legível.', ['Tipo','Imagem','Voz']),('03','Sistema','Diretrizes para que a equipe continue produzindo com a mesma gravidade.', ['UI','Motion','Guia'])], cta='Dar forma à marca'),
 'documentacao': dict(title='Documentação', kicker='Arquivo operacional', chapter='20', headline='Operar bem<br>também é<br><em style="color:var(--void-red);font-style:normal">comunicar.</em>', deck='Documentação é a camada que transforma decisões individuais em contexto compartilhado. Aqui está o mapa para explorar o universo técnico da Black Void.', cards_title='Entradas do arquivo', cards=[('DEVELOPER HUB','Comece pelo mapa','Visão geral das ferramentas, padrões e caminhos de integração.'),('API REFERENCE','Leia a superfície','Endpoints, autenticação e contratos para sistemas que precisam conversar.'),('STATUS','Veja o pulso','Disponibilidade, mudanças e notas de operação em um só lugar.')], cta='Abrir o Developer Hub'),
 'Starter': dict(title='Starter', kicker='Primeira camada', chapter='21', headline='Começar pequeno<br>sem pensar<br><em style="color:var(--void-red);font-style:normal">pequeno.</em>', deck='Uma frente concentrada para organizar marca, presença digital ou uma automação que já deveria estar funcionando.', cards_title='O que cabe na primeira entrega', cards=[('DIREÇÃO','Diagnóstico e tese','Mapeamento do problema, hipótese de valor e primeiro recorte.'),('DESIGN','Interface com intenção','Sistema visual e experiência que já nascem com espaço para evoluir.'),('BASE','Handoff legível','Documentação e próximos movimentos para o time seguir sem dependência.')], cta='Falar sobre o Starter'),
}

MEDIA_BY_SLUG = {
    'casos': CASE, 'carreira': CULTURE, 'blog': CASE, 'recursos': ECOSYSTEM, 'faq': CULTURE,
    'planos': HERO, 'tecnologias': ECOSYSTEM, 'cybersecurity': URBAN, 'automacao': CASE,
    'documentacao': ECOSYSTEM, 'Starter': HERO,
}
SCENE_BY_SLUG = {
    'ecossistema': 'ecosystem', 'kira': 'product', 'servicos': 'services',
    'ia': 'flow', 'automacao': 'flow', 'desenvolvimento': 'flow',
    'infraestrutura': 'flow', 'cybersecurity': 'flow', 'branding': 'flow',
    'portfolio': 'proof', 'casos': 'proof', 'sobre': 'culture', 'team': 'culture',
    'carreira': 'culture', 'blog': 'culture', 'recursos': 'archive', 'faq': 'archive',
    'planos': 'archive', 'tecnologias': 'archive', 'documentacao': 'archive', 'Starter': 'archive',
}
for slug, config in COMMON.items():
    if slug in SCENE_BY_SLUG:
        config['mode'] = SCENE_BY_SLUG[slug]
    if not config.get('image') and slug in MEDIA_BY_SLUG:
        config['image'] = MEDIA_BY_SLUG[slug]
        config['image_alt'] = f'Imagem editorial da página {config["title"]}'
        config['image_title'] = config.get('image_title', f'{config["title"]} como matéria.')
        config['image_note'] = config.get('image_note', 'Uma camada visual para tornar a ideia mais próxima, concreta e memorável.')
    (PAGES / f'{slug}.html').write_text(editorial_page(config), encoding='utf-8')

(ROOT / 'index.html').write_text(home_page(), encoding='utf-8')

def contact_page():
    body = hero('Contato', 'Dê um nome<br>ao próximo <em style="color:var(--void-red);font-style:normal">movimento.</em>', 'Conte o que está difícil, o que já tentou e o que precisa ser verdade depois da primeira entrega.', '22')
    body += '''<section><div class="wrap"><div class="split"><div><span class="eyebrow">Briefing aberto</span><p class="lead" style="margin-top:24px">Não precisa chegar com um escopo fechado. Uma boa pergunta já é material suficiente para começar.</p><p class="meta" style="margin-top:30px;color:var(--muted)">Resposta inicial em até dois dias úteis / contato@blackvoid.studio</p></div><form class="card" action="mailto:contato@blackvoid.studio" method="post" enctype="text/plain"><label class="meta" for="name">Seu nome</label><input id="name" name="nome" required placeholder="Como podemos chamar você?"><label class="meta" for="email">E-mail</label><input id="email" name="email" type="email" required placeholder="voce@empresa.com"><label class="meta" for="message">O que precisa mudar?</label><textarea id="message" name="mensagem" rows="6" required placeholder="Conte o problema, o contexto e o que seria uma boa primeira decisão."></textarea><button class="btn" type="submit">Enviar briefing ↗</button></form></div></div></section>'''
    return shell('Contato', 'Abra uma conversa com a Black Void sobre IA, software, infraestrutura ou design.', body + cta('Voltar ao início'))

(PAGES / 'contato.html').write_text(contact_page(), encoding='utf-8')

def systems_page():
    body = hero('Arquivo operacional', 'Sistemas que<br>continuam depois<br>da <em style="color:var(--void-red);font-style:normal">apresentação.</em>', 'Algumas ideias precisam de uma superfície para operar. Este é o mapa dos sistemas que a Black Void está construindo, testando e preparando para ganhar continuidade.', '22')
    body += '''<section class="scene-section scene-archive"><div class="wrap"><div class="scene-header"><span class="eyebrow">Mapa de continuidade</span><span class="meta">SYSTEMS / 2026</span></div><div class="archive-shelves"><div class="archive-shelf"><span>01</span><strong>SINAL</strong><em>O que mudou?</em></div><div class="archive-shelf"><span>02</span><strong>DECISÃO</strong><em>O que merece prioridade?</em></div><div class="archive-shelf"><span>03</span><strong>OPERAÇÃO</strong><em>Como o time segue?</em></div><div class="archive-shelf"><span>04</span><strong>PROVA</strong><em>O que continua de pé?</em></div></div></div></section>'''
    body += '''<section><div class="wrap"><div class="section-head"><div><span class="eyebrow">Entradas do arquivo</span><h2 class="h-lg" style="margin-top:18px">Não é uma vitrine.<br>É um mapa de estado.</h2></div><p class="lead">Cada entrada informa o que o sistema faz, em que ambiente existe e qual é o próximo limite antes de ser compartilhado.</p></div><div class="grid-2 reveal-stagger"><article class="card reveal"><span class="tag">ATLAS COMMAND / 2026</span><h3>Uma superfície de decisão.</h3><p>Prioridades autenticadas, contexto e eventos para transformar sinais dispersos em ações que podem ser acompanhadas.</p><div style="margin-top:20px"><span class="pill">PRÉVIA</span><span class="pill">ACESSO RESTRITO</span></div><a class="text-link" href="https://atlas-command-nine.vercel.app" style="margin-top:22px">Abrir prévia ↗</a></article><article class="card reveal"><span class="tag">TMS / 2026</span><h3>Operação logística em camadas.</h3><p>Tracker, painel administrativo e portal do cliente separados por responsabilidade, acesso e consequência.</p><div style="margin-top:20px"><span class="pill">STAGING</span><span class="pill">PAINÉIS SEPARADOS</span></div><a class="text-link" href="https://tms-painel-adm.vercel.app" style="margin-top:22px">Abrir painel administrativo ↗</a><a class="text-link" href="https://tms-painel-client.vercel.app" style="margin-top:12px">Abrir portal do cliente ↗</a></article><article class="card reveal"><span class="tag">TRACKERTMS / DISTRIBUIÇÃO</span><h3>Um ponto de entrada para o dispositivo.</h3><p>Site estático para distribuir o APK assinado do Tracker, sem armazenar chaves de assinatura na interface.</p><div style="margin-top:20px"><span class="pill">DOWNLOAD</span><span class="pill">RELEASE ASSINADO</span></div><a class="text-link" href="https://tms-downloads.vercel.app" style="margin-top:22px">Abrir distribuição ↗</a></article><article class="card reveal"><span class="tag">LABORATÓRIO / DEMO</span><h3>O que ainda está aprendendo.</h3><p>Backends de demonstração são úteis para contar uma história, mas não devem ser confundidos com operação multi-tenant ou produção.</p><div style="margin-top:20px"><span class="pill">SOMENTE DEMO</span><span class="pill">NÃO PROMOVER</span></div></article></div></div></section>'''
    body += '''<section><div class="wrap"><div class="section-head"><div><span class="eyebrow">Critério de publicação</span><h2 class="h-lg" style="margin-top:18px">Compartilhar também<br>é saber <em style="color:var(--void-red);font-style:normal">limitar.</em></h2></div><p class="lead">O catálogo não expõe tokens, bancos, dados de clientes, endpoints de recuperação ou ações administrativas. Ele aponta para superfícies com o nível de acesso explicitado.</p></div><div class="table-list"><div class="table-row reveal"><span class="num">01</span><strong>Privado</strong><p>Autenticação e validação do titular ainda são necessárias.</p><span class="tag">ATLAS</span></div><div class="table-row reveal"><span class="num">02</span><strong>Staging</strong><p>Backend, CORS, login, isolamento e healthcheck devem ser confirmados.</p><span class="tag">TMS</span></div><div class="table-row reveal"><span class="num">03</span><strong>Distribuição</strong><p>Somente releases HTTPS assinados e configurados.</p><span class="tag">TRACKER</span></div></div></div></section>'''
    body += cta('Voltar ao portfólio')
    return shell('Sistemas', 'Atlas Command, TMS e sistemas em operação da Black Void Studio.', body)

(PAGES / 'sistemas.html').write_text(systems_page(), encoding='utf-8')

def arthur_page():
    body = hero('Microsite de equipe', 'Arthur<br><em style="color:var(--void-red);font-style:normal">Miyazaki.</em>', 'Um capítulo independente sobre engenharia, IA e sistemas interativos. A experiência completa vive no microsite Signal Void.', '23')
    body += f'''<section><div class="wrap"><div class="split split--wide"><div><span class="eyebrow">Signal Void</span><p class="lead" style="margin-top:24px">Uma experiência imersiva que acompanha a forma como Arthur pensa: entre arquitetura, software, interfaces e presença humana.</p></div><div class="feature-art"><img src="{CULTURE}" alt="Retrato editorial abstrato de um engenheiro" loading="lazy"><div><span class="tag">ARTHUR / 2026</span><h3>Entre o código e a matéria.</h3><a class="btn ghost" style="margin-top:20px" href="../equipe/arthur/index.html">Entrar no microsite ↗</a></div></div></div></div></section>'''
    return shell('Arthur Miyazaki', 'Microsite editorial de Arthur Miyazaki.', body + cta('Voltar ao arquivo'))

(PAGES / 'arthur.html').write_text(arthur_page(), encoding='utf-8')

def docs_page(slug, title, kicker, headline, intro, entries):
    body = hero(kicker, headline, intro, 'DOC')
    rows = ''.join(f'<article class="chapter reveal"><span class="chapter-index">{i:02d} / DOC</span><div><h3>{name}</h3><p>{desc}</p><a class="btn ghost" href="{href}" style="margin-top:22px">Abrir página ↗</a></div></article>' for i, (name, desc, href) in enumerate(entries, 1))
    body += f'''<section><div class="wrap"><div class="section-head"><div><span class="eyebrow">{kicker}</span><h2 class="h-lg" style="margin-top:18px">Leia pelo<br>ponto certo.</h2></div><p class="lead">A documentação também é parte da experiência: clara para começar, precisa para continuar.</p></div><div>{rows}</div></div></section>'''
    return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — Black Void</title><link rel="icon" href="../pages/assets/img/logo.png"><link rel="stylesheet" href="../pages/assets/css/style.css"></head><body><div id="loader"><img class="ldr-mark" src="../pages/assets/img/logo.png" alt=""><div class="ldr-word">BLACK VOID / DOCS</div><div class="ldr-bar"><i></i></div></div><div data-include="../components/menu-superior.html"></div><main>{body}</main><footer><div data-include="../components/menu.html"></div></footer><script src="../components/include.js"></script><script src="../pages/assets/js/main.js"></script></body></html>'''

DOC_ENTRIES = {
 'developer-hub.html': ('Developer Hub', 'Entrada técnica', 'Um lugar para começar<br>sem perder o <em style="color:var(--void-red);font-style:normal">contexto.</em>', 'Mapas, contratos e caminhos para entender como as peças da Black Void se encaixam.', [('Documentação', 'Visão geral do arquivo e dos princípios de integração.', 'documentation.html'), ('API Reference', 'Contratos e superfícies para serviços que precisam conversar.', 'api-reference.html'), ('SDKs', 'Pacotes, exemplos e caminhos para começar a construir.', 'sdks.html')]),
 'documentation.html': ('Documentation', 'Guias de operação', 'A primeira pergunta<br>é sempre<br><em style="color:var(--void-red);font-style:normal">onde?</em>', 'Guias curtos para atravessar o sistema sem depender de adivinhação.', [('Começar', 'A estrutura geral e a sequência recomendada para novos projetos.', 'developer-hub.html'), ('Status', 'Veja o pulso dos serviços e as alterações recentes.', 'status.html'), ('Roadmap', 'O que está em pesquisa, construção e observação.', 'roadmap.html')]),
 'api-reference.html': ('API Reference', 'Contratos e endpoints', 'Superfícies claras<br>para sistemas que<br><em style="color:var(--void-red);font-style:normal">conversam.</em>', 'Referências de API devem reduzir dúvida, não criar uma nova camada de tradução.', [('Autenticação', 'Tokens, escopos e limites de acesso.', 'documentation.html'), ('Eventos', 'Como receber sinais sem perder ordem ou contexto.', 'status.html'), ('Erros', 'Respostas previsíveis para cenários que não são felizes.', 'changelog.html')]),
 'sdks.html': ('SDKs', 'Kits de construção', 'Menos atrito<br>entre a ideia<br>e o <em style="color:var(--void-red);font-style:normal">primeiro request.</em>', 'Kits e exemplos para transformar uma integração em uma capacidade que o time consegue sustentar.', [('JavaScript', 'Para interfaces e serviços web que precisam de ritmo.', 'api-reference.html'), ('Python', 'Para dados, agentes e rotinas operacionais.', 'api-reference.html'), ('Exemplos', 'Pequenos pontos de partida para grandes sistemas.', 'documentation.html')]),
 'changelog.html': ('Changelog', 'Registro de mudanças', 'O sistema muda.<br>O arquivo<br><em style="color:var(--void-red);font-style:normal">registra.</em>', 'Mudanças importantes, decisões e o contexto que ajuda a ler cada versão.', [('2026.06', 'Novo mapa de navegação, sistema visual e documentação editorial.', 'roadmap.html'), ('2026.04', 'Camada de observabilidade e documentação de integração revisadas.', 'status.html'), ('Arquivo', 'Notas antigas e decisões que ainda sustentam o sistema.', 'documentation.html')]),
 'open-source.html': ('Open Source', 'Projetos abertos', 'Conhecimento<br>cresce quando<br>fica <em style="color:var(--void-red);font-style:normal">visível.</em>', 'Um espaço para separar o que é ferramenta interna, o que é pesquisa e o que pode ser compartilhado.', [('Ferramentas', 'Pequenos instrumentos que nasceram de problemas reais.', 'developer-hub.html'), ('Pesquisa', 'Experimentos que ainda estão aprendendo a ser produtos.', 'roadmap.html'), ('Contribuição', 'Como conversar com o arquivo e melhorar uma peça.', 'documentation.html')]),
 'roadmap.html': ('Roadmap', 'O que vem depois', 'O futuro não é<br>uma promessa.<br>É um <em style="color:var(--void-red);font-style:normal">sistema.</em>', 'O que está em construção deve poder ser lido, questionado e reposicionado.', [('Agora', 'Sistemas de IA aplicados, documentação e presença digital coerente.', 'documentation.html'), ('Depois', 'Mais telemetria, mais automação e mais caminhos de integração.', 'status.html'), ('Pesquisa', 'Novas interfaces para operar com contexto em vez de ruído.', 'open-source.html')]),
 'status.html': ('Status', 'Pulso operacional', 'Veja o que<br>está de pé<br>e o que <em style="color:var(--void-red);font-style:normal">mudou.</em>', 'Transparência operacional começa com uma linguagem simples para o estado das coisas.', [('Core systems', 'Operação estável / último registro agora.', 'documentation.html'), ('Kira AI', 'Pesquisa e evolução contínuas / camada em expansão.', 'developer-hub.html'), ('Archive', 'Documentação e páginas em revisão editorial.', 'changelog.html')]),
 'brand.html': ('Brand Assets', 'Sistema de marca', 'A forma também<br>é parte do<br><em style="color:var(--void-red);font-style:normal">sistema.</em>', 'Diretrizes para manter a identidade Black Void coerente quando a página muda de escala.', [('Marca', 'Símbolo, wordmark e áreas de respiro.', 'documentation.html'), ('Tipografia', 'Instrument Serif, Manrope e Space Mono em contexto.', 'documentation.html'), ('Cor', 'Carvão, osso, vermelho mineral e metal fosco.', 'documentation.html')]),
 'careers.html': ('Careers', 'Trabalhe com a gente', 'Pessoas para<br>problemas que<br>não cabem em <em style="color:var(--void-red);font-style:normal">um cargo.</em>', 'Uma nota técnica sobre como pensamos colaboração, autoria e profundidade.', [('Como trabalhamos', 'Clareza, autonomia, crítica e proximidade com o problema.', 'documentation.html'), ('O que buscamos', 'Curiosidade suficiente para cruzar disciplina sem perder rigor.', 'roadmap.html'), ('Contato', 'Envie uma apresentação com contexto, não apenas um currículo.', '../pages/contato.html')]),
}
for filename, (title, kicker, headline, intro, entries) in DOC_ENTRIES.items():
    (DOCS / filename).write_text(docs_page(filename, title, kicker, headline, intro, entries), encoding='utf-8')

(ROOT / 'black-void-pages' / '404.html').write_text('''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>404 — Black Void</title><link rel="stylesheet" href="../pages/assets/css/style.css"></head><body><main><section class="page-hero"><div class="wrap"><span class="eyebrow">Erro de arquivo</span><h1 class="h-xl" style="margin-top:22px">O caminho<br>se perdeu no<br><em style="color:var(--void-red);font-style:normal">vazio.</em></h1><p class="lead" style="margin-top:28px">A página que você procurou não está disponível neste endereço.</p><a class="btn" href="../index.html" style="margin-top:34px">Voltar ao início ↗</a></div></section></main></body></html>''', encoding='utf-8')
